site_name: AnkaFlow Documentation
site_url: https://example.com/docs
theme:
  name: material

markdown_extensions:
  - toc:  # Enables a Table of Contents (TOC) for each page
      permalink: true  # Adds a permalink to each header for easy linking
  - tables  # Enables rendering of tables in Markdown

# Directory where Markdown files are located (default is 'docs')
docs_dir: docs  # Directory containing your Markdown files, adjust if your docs are elsewhere
site_dir: site

extra:
  static_dir:
    - demo
  analytics:
    provider: google
    property: G-KTHG2QG391
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting started: getting-started.md
  - Guides:
      - Browser setup: browser-readme.md
      - Custom connection: custom-connection.md
      - Using with Motherduck: motherduck.md
  - API:
      - Pipeline API: api/ankaflow.models.md
      - Duct API: api/ankaflow.md
  - Browser demo: demo/index.html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
            signature_crossrefs: true
            unwrap_annotated: true
            separate_signature: true
            docstring_style: google
            show_signature_annotations: true
            merge_init_into_class: true
            members_order: alphabetical
            scoped_crossrefs: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: false
            show_bases: true
            show_labels: false
            members: true
            show_source: false
            docstring_section_style: table
            modernize_annotations: true
            filters:
              - "!^_"
              - "!^__"
              - "!model_config"
              - "!^test"
              - "!^tmp"
              - "!^itest"
              - "!^[Tt]est"
  - autorefs:
      resolve_closest: true
  - exclude:
      glob:
        - tmp/*
        - tmp_*.py
        - test_*.py
        - itest_*.py
      regex:
        - '.*\.(tmp|bin|tar|log|gz|pdf)$'
